export const corpus: { text: string; meta: Record<string, string> }[] = [
  { text: 'Nothing in this world can take the place of persistence.', meta: { author: 'Calvin Coolidge' } },
  { text: 'The only way to do great work is to love what you do.', meta: { author: 'Steve Jobs' } },
  { text: 'In the middle of difficulty lies opportunity.', meta: { author: 'Albert Einstein' } },
  { text: 'It is not the strongest of the species that survives, but the most adaptable.', meta: { author: 'Charles Darwin (paraphrase)' } },
  { text: 'A friend is someone who knows all about you and still loves you.', meta: { author: 'Elbert Hubbard' } },
  { text: 'The journey of a thousand miles begins with one step.', meta: { author: 'Lao Tzu' } },
  { text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', meta: { author: 'Winston Churchill' } },
  { text: 'Loyalty and devotion lead to bravery.', meta: { author: 'Morihei Ueshiba' } },
  { text: 'The best time to plant a tree was 20 years ago. The second best time is now.', meta: { author: 'Chinese proverb' } },
  { text: 'Whether you think you can or you think you can’t, you’re right.', meta: { author: 'Henry Ford' } },
  { text: 'Hardships often prepare ordinary people for an extraordinary destiny.', meta: { author: 'C.S. Lewis' } },
  { text: 'I have not failed. I’ve just found 10,000 ways that won’t work.', meta: { author: 'Thomas Edison' } },
  { text: 'Wisdom begins in wonder.', meta: { author: 'Socrates' } },
  { text: 'An investment in knowledge pays the best interest.', meta: { author: 'Benjamin Franklin' } },
  { text: 'True friends stab you in the front.', meta: { author: 'Oscar Wilde' } },
  { text: 'The only true wisdom is in knowing you know nothing.', meta: { author: 'Socrates' } },
  { text: 'Perseverance is failing 19 times and succeeding the 20th.', meta: { author: 'Julie Andrews' } },
  { text: 'Stay close to people who feel like sunlight.', meta: { author: 'Unknown' } },
  { text: 'Difficult roads often lead to beautiful destinations.', meta: { author: 'Zig Ziglar' } },
  { text: 'Learning never exhausts the mind.', meta: { author: 'Leonardo da Vinci' } },
]
